name: deploy-cube-sandbox-manual
run-name: "Triggered by ${{ github.actor }}/${{ github.triggering_actor }} deploying version: ${{ inputs.archive }}"
on:
  workflow_dispatch:
    inputs:
      archive:
        description: 'Which version of archive to deploy'
        required: true

jobs:
    deploy-cube-sandbox:
      runs-on: ubuntu-latest
      environment: ${{ vars.ENVIRONMENT }}
      steps:
        - name: Download repository
          uses: actions/checkout@v4

        - name: Show variables
          run: |
            echo ${{ github.ref }}
            echo "Running by the user: ${{ github.actor }}/${{ github.triggering_actor }} with version: ${{ inputs.archive }} on date: $(date +'%A, %b %d, %Y %I:%M %p')"
            cd archive
            zip -r archive.zip .
            mv archive.zip ..


        - name: 'Upload directory'
          uses: actions/upload-artifact@v3
          with:
            name: directory
            path: archive
            retention-days: 5

        - name: 'Upload file'
          uses: actions/upload-artifact@v3
          with:
            name: file
            path: archive.txt
            retention-days: 5

        - name: 'Upload zip'
          uses: actions/upload-artifact@v3
          with:
            name: zip
            path: archive.zip
            retention-days: 5
            
    download-artifact:
      needs: [deploy-cube-sandbox]
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3

        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: directory

        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: file

        - name: Download artifacts
          uses: actions/download-artifact@v3
          with:
            name: zip

        - name: Extract
          run: |
            ls -lah
            ls -alh directory
            ls -lah file
            ls -alh zip


