name: deploy-cube-sandbox-manual
run-name: "Triggered by ${{ github.actor }}/${{ github.triggering_actor }} deploying version: ${{ inputs.archive }}"
on:
  workflow_dispatch:
    inputs:
      archive:
        description: 'Which version of archive to deploy'
        required: true

jobs:
    deploy-cube-sandbox:
      runs-on: ubuntu-latest
      environment: ${{ vars.ENVIRONMENT }}
      steps:
        - name: Download repository
          uses: actions/checkout@v4

        - name: Show variables
          run: |
            echo ${{ github.ref }}
            echo "Running by the user: ${{ github.actor }}/${{ github.triggering_actor }} with version: ${{ inputs.archive }} on date: $(date +'%A, %b %d, %Y %I:%M %p')"

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: archive
            retention-days: 5
            
    download-artifact:
      runs-on: ubuntu-latest
      steps:
        - name: Download a single artifact
          uses: actions/download-artifact@v3
          with:
            name: my-artifact
        
        - name: Extract
          run: |
            ls -lah


