name: deploy-cube-sandbox-manual
run-name: "Triggered by ${{ github.actor }}/${{ github.triggering_actor }} deploying version: ${{ inputs.archive }}"
on:
  workflow_dispatch:
    inputs:
      archive:
        description: 'Which version of archive to deploy'
        required: true

jobs:
    deploy-cube-sandbox:
      runs-on: ubuntu-latest
      environment: ${{ vars.ENVIRONMENT }}
      steps:
        - name: Download repository
          uses: actions/checkout@v4

        - name: Download archive
          run: |
            echo "Downloading archive ${{ inputs.archive}} from environment ${{ vars.ENVIRONMENT }}"

        - name: Show variables
          run: |
            echo "Running by the user: ${{ github.actor }} --- if rerun user is ${{ github.triggering_actor }}"

